name: Conditional-workflow
on: [push]
jobs:
  hello-world:
    if: ${{ github.repository == 'git-padkirk/ifcondition' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello World!"
  goodbye-world:
    runs-on: ubuntu-latest
    steps:
      - name: 'Goodbye World'
        run: echo "Goodbye World"
      - name: Print repository
        run: echo ${{ github.repository }}
