name: Inputs example
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Inputs regarding the environment'
        required: true
        default: production
        type: choice
        options:
          - production
          - QA
          - Staging
          - Dev        

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployed on ${{ github.event.inputs.environment }} environment"
    
