name: Random Number
on: [push]
jobs:
  random_number_generation:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 0 or 1
        id: number-generator
        run: echo "random_number = $ (( $RANDOM % 2 ))" >> $GITHUB_OUTPUT
      - name: Pass or fail
        run: |
          if [[ ${{ steps.number-generator.outputs.random_number }} == 0 ]]; 
          then exit 0; else exit 1; fi
