name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the artifact file
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
           name: ${{ inputs.artifact_name }}
      - name: List artifacts
        run: ls
      - name: Depoy application
        run: echo "Deploying and initializing..."
        
